In [189]:
%load_ext autoreload
%autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [190]:
from utils import *
from mfcc_label import *
from get_prob import get_label_df
from config import *
from prepare_data import *
from joblib import load

In [142]:
prepare_data(TEST_PHN_PATH, TEST_WAV_PATH)

For start 51600 and end 52000, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 51600 and end 52000

,mfcc,label,state_weights
0,"[-730.5058, 45.045067, -24.230473, -16.595982,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
1,"[-714.74677, 51.683174, -20.392345, -13.274165...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
2,"[-720.12866, 46.353207, -18.542915, -15.895822...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
3,"[-726.85284, 38.16919, -21.354225, -16.98072, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
4,"[-733.83295, 39.958935, -22.630146, -19.272156...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
...,...,...,...
640,"[-771.8571, 31.682955, 16.981308, 15.85192, 18...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
641,"[-770.94904, 33.92119, 22.370777, 20.100182, 2...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
642,"[-770.55426, 33.699005, 22.837954, 21.1912, 19...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
643,"[-770.9694, 39.23896, 30.920292, 26.336763, 22...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}
644,"[-773.8508, 36.92386, 31.087677, 26.386032, 23...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",{'h#': 1.0}

In [157]:
file_info = prepare_batch_matrix(TEST_WRD_PATH, TEST_PHN_PATH, TEST_WAV_PATH, 20)

For start 51600 and end 52000, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 51600 and end 52000
For start 51600 and end 52000, there is no time-overlapping row.

In [170]:
from joblib import load
len(load('processed_data/test_data_for_hmm.joblib').keys())

29

In [179]:
test_dict = load('processed_data/test_data_for_hmm.joblib')

In [180]:
test_dict[('timit/data/TRAIN/DR2/FPJF0/SX146.WAV', 'timit/data/TRAIN/DR2/FPJF0/SX146.PHN', 'timit/data/TRAIN/DR2/FPJF0/SX146.WRD')]

                                              Emission
0    [-17.434429387114346, -24.28465266387969, -11....
1    [-15.974292973540127, -23.437774612121878, -12...
2    [-21.026769856474697, -27.69697947662383, -12....
3    [-20.263733128569424, -26.89197344940215, -12....
4    [-19.546344975493252, -26.294813110046682, -12...
..                                                 ...
457  [-8.561793545744717, -14.356719924621878, -10....
458  [-13.352533558867275, -21.576829864197073, -11...
459  [-17.87524245168954, -26.058099700622854, -11....
460  [-17.648552159331143, -25.21513934295684, -10....
461  [-12.79404471304208, -20.922948791199026, -11....

[462 rows x 1 columns]

In [191]:
batch_matrix_train(dataset_type="test")

For start 36960 and end 37360, there is no time-overlapping row.
For start 45760 and end 46160, there is no time-overlapping row.
For start 62960 and end 63360, there is no time-overlapping row.
For start 31760 and end 32160, there is no time-overlapping row.
For start 0 and end 400, there is no time-overlapping row.
For start 80 and end 480, there is no time-overlapping row.
For start 160 and end 560, there is no time-overlapping row.
For start 240 and end 640, there is no time-overlapping row.
For start 320 and end 720, there is no time-overlapping row.
For start 400 and end 800, there is no time-overlapping row.
For start 480 and end 880, there is no time-overlapping row.
For start 560 and end 960, there is no time-overlapping row.
For start 640 and end 1040, there is no time-overlapping row.
For start 720 and end 1120, there is no time-overlapping row.
For start 800 and end 1200, there is no time-overlapping row.
For start 880 and end 1280, there is no time-overlapping row.
For start 960 and end 1360, there is no time-overlapping row.
For start 1040 and end 1440, there is no time-overlapping row.
For start 1120 and end 1520, there is no time-overlapping row.
For start 1200 and end 1600, there is no time-overlapping row.
For start 1280 and end 1680, there is no time-overlapping row.
For start 1360 and end 1760, there is no time-overlapping row.
For start 1440 and end 1840, there is no time-overlapping row.
For start 1520 and end 1920, there is no time-overlapping row.
For start 1600 and end 2000, there is no time-overlapping row.
For start 1680 and end 2080, there is no time-overlapping row.
For start 1760 and end 2160, there is no time-overlapping row.
For start 1840 and end 2240, there is no time-overlapping row.
For start 1920 and end 2320, there is no time-overlapping row.
For start 2000 and end 2400, there is no time-overlapping row.
For start 43840 and end 44240, there is no time-overlapping row.
For start 51600 and end 52000, there is no time-overlapping row.
For start 56240 and end 56640, there is no time-overlapping row.

,input,emission_matrix,label
0,timit/data/TRAIN/DR2/FPJF0/SX146.WAV,"[[-22.766163090727627, -22.163231114409268, -1...",0
1,timit/data/TRAIN/DR2/FPJF0/SX146.WAV,"[[-7.861279706023036, -6.426441411040126, -4.7...",0
2,timit/data/TRAIN/DR2/FPJF0/SX146.WAV,"[[-8.228961209318935, -7.443621853850185, -4.2...",0
3,timit/data/TRAIN/DR2/FPJF0/SX146.WAV,"[[-20.710293034575283, -19.21895049001962, -16...",0
4,timit/data/TRAIN/DR2/FPJF0/SX146.WAV,"[[-23.36139319326669, -20.873726109526455, -12...",0
...,...,...,...
720,timit/data/TRAIN/DR3/FJLR0/SX61.WAV,"[[-8.528169850371182, -2.8450290956714737, -3....",1
721,timit/data/TRAIN/DR3/FJLR0/SX61.WAV,"[[-2.8450290956714737, -3.942174653075038, -7....",1
722,timit/data/TRAIN/DR3/FJLR0/SX61.WAV,"[[-3.942174653075038, -7.874497632048427, -9.4...",1
723,timit/data/TRAIN/DR3/FJLR0/SX61.WAV,"[[-7.874497632048427, -9.49452135946542, -9.36...",1
724,timit/data/TRAIN/DR3/FJLR0/SX61.WAV,"[[-9.49452135946542, -9.366847256682217, -8.01...",1

In [159]:
df_train_batch = batch_matrix_train()

For start 43840 and end 44240, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 43840 and end 44240
For start 43840 and end 44240, there is no time-overlapping row.
For start 56240 and end 56640, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 56240 and end 56640
For start 56240 and end 56640, there is no time-overlapping row.
For start 59200 and end 59600, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 59200 and end 59600
For start 59200 and end 59600, there is no time-overlapping row.
For start 52240 and end 52640, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 52240 and end 52640
For start 52240 and end 52640, there is no time-overlapping row.
For start 42480 and end 42880, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 42480 and end 42880
For start 42480 and end 42880, there is no time-overlapping row.
For start 49040 and end 49440, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 49040 and end 49440
For start 49040 and end 49440, there is no time-overlapping row.
For start 39840 and end 40240, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 39840 and end 40240
For start 39840 and end 40240, there is no time-overlapping row.
For start 35440 and end 35840, there is no time-overlapping row.
Caution: There is no time-overlapping rows for start 35440 and end 35840
For start 35440 and end 35840, there is no time-overlapping row.

In [160]:
df_train_batch

,input,emission_matrix,label
0,timit/data/TRAIN/DR3/MDWM0/SX376.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",0
1,timit/data/TRAIN/DR3/MDWM0/SX376.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",0
2,timit/data/TRAIN/DR3/MDWM0/SX376.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",0
3,timit/data/TRAIN/DR3/MDWM0/SX376.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",0
4,timit/data/TRAIN/DR3/MDWM0/SX376.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",0
...,...,...,...
695,timit/data/TRAIN/DR7/MREM0/SX61.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",1
696,timit/data/TRAIN/DR7/MREM0/SX61.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",1
697,timit/data/TRAIN/DR7/MREM0/SX61.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",1
698,timit/data/TRAIN/DR7/MREM0/SX61.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",1
699,timit/data/TRAIN/DR7/MREM0/SX61.WAV,"[[-23.025850929940457, -23.025850929940457, -2...",1

In [161]:
df_train_batch['label'].value_counts()

label
0    554
1    146
Name: count, dtype: int64